Remove some lambda expressions
These are causing `NoSuchMethodError` on application startup
(see https://bugs.openjdk.java.net/browse/JDK-8161588 for more details)
which can have a small impact on startup performance

N.B. I only replaced the code for the instances
that were causing the issue at the startup of a
Quarkus application that uses Vert.x