Exception cause lost if result already complete.
It's impossible to fix the original issue without the cause. Found this while trying to debug a test failure:

Caught unexpected Throwable
java.lang.IllegalStateException: Result is already complete: failed
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:121)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:277)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Signed-off-by: Thomas Segismont <tsegismont@gmail.com>