Fixed io.vertx.test.core.MetricsTest.testThreadPoolMetricsWithWorkerVerticle
java.lang.AssertionError: expected:<100> but was:<101>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
	at io.vertx.test.core.MetricsTest.testWithWorkerVerticle(MetricsTest.java:982)
	at io.vertx.test.core.MetricsTest.testThreadPoolMetricsWithWorkerVerticle(MetricsTest.java:919)

When testComplete is called, the main thread can start to check the pool metrics, but the worker thread may not have updated the metrics yet.

Signed-off-by: Thomas Segismont <tsegismont@gmail.com>